# IEOR 290 Data-X: HW2 (Feb. 2, 2017)
### Kresch, Rachelle | SID: 20022676

## Problem 1: Numpy

#1. Create	two	numpy arrays (a and	b).	a should	be	all	integers	between	10-19	(inclusive), and b should	be	ten	evenly	spaced	numbers	between	1-7.	Print	all	the	results	below:

In [5]:
import numpy as np

a=np.arange(10,20, 1)
b=np.linspace(1,7,10)

print(a)
print(b)

[10 11 12 13 14 15 16 17 18 19]
[ 1.          1.66666667  2.33333333  3.          3.66666667  4.33333333
  5.          5.66666667  6.33333333  7.        ]


#1. Square	all	the	elements	in	both	arrays	(element-wise)

In [17]:
a_new = np.square(a)
b_new = np.square(b)

print(a_new)
print(b_new)

[100 121 144 169 196 225 256 289 324 361]
[  1.           2.77777778   5.44444444   9.          13.44444444
  18.77777778  25.          32.11111111  40.11111111  49.        ]


#2. Add	both	the	squared	arrays

In [8]:
my_sums= a_new+b_new
print(my_sums)

[ 101.          123.77777778  149.44444444  178.          209.44444444
  243.77777778  281.          321.11111111  364.11111111  410.        ]


#3. Sum	the	even	elements	of	the	added	array.

In [9]:
##Assume this means to add the even numbers in the list and not based on the index values

evens = 0

for i in range(1, len(my_sums)):    
    if my_sums[i]%2==0:
        evens = evens + my_sums[i]
        
print(evens)

588.0


#4. Take	the	square	root	of	the	added	array	(element-wise	square	root)

In [10]:
print(np.sqrt(my_sums))

[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]


#2. Append	b to	a,	reshape	the	appended	array	so	that	it	is	a	5x4,	2d	array	and	store	the	results	in	a	variable	called	m.	Print	m.

In [12]:
##Assume 5 by 4 means 5 rows and 4 columns
m = np.reshape(np.append(a,b), (5,4))
print(m)

[[ 10.          11.          12.          13.        ]
 [ 14.          15.          16.          17.        ]
 [ 18.          19.           1.           1.66666667]
 [  2.33333333   3.           3.66666667   4.33333333]
 [  5.           5.66666667   6.33333333   7.        ]]


#3. Extract	the	second	and	the	third	column	of	the	m matrix.	Store	the	resulting	5x2	matrix	in	a new	variable	called	m2.	Print	m2.

In [13]:
m2 = m[:,(1,2)]
print(m2)

[[ 11.          12.        ]
 [ 15.          16.        ]
 [ 19.           1.        ]
 [  3.           3.66666667]
 [  5.66666667   6.33333333]]


#4. Take	the	dot	product	of	m2T and	m	store	the	results	in	a	matrix	called	m3.	Print	m3.

In [14]:
m3 = np.dot(np.transpose(m2),m)
print(m3)

[[ 697.33333333  748.11111111  437.88888889  482.33333333]
 [ 402.22222222  437.88888889  454.55555556  489.88888889]]


#5. Round	the	m3 matrix	to	two	decimal	points.	Store	the	result	in	place	and	print	the	new	m3.

In [15]:
m3=np.round(m3,2)
print(m3)

[[ 697.33  748.11  437.89  482.33]
 [ 402.22  437.89  454.56  489.89]]


#6. Sort	the	m3 array	so	that	the	highest	value	is	at	the	top	left,	the	next	highest	value	to	the	right	of	the	highest,	and	the	lowest	value	is	at	the	bottom	right.	Print	the	sorted	m3	array

In [22]:
## Assume we want to keep m3's original shape
temp = np.sort(m3,None)[::-1]
m3 = np.reshape(temp,(2,4))
print(m3)

[[ 748.11  697.33  489.89  482.33]
 [ 454.56  437.89  437.89  402.22]]
